[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "18.19.0"
  YARN_VERSION = "1.22.21"
[[redirects]]
  from = "https://hmsk.me/more"
  to = "https://text.hmsk.me/more"
  status = 302
  force = true
